"""empty message

Revision ID: 2148d33427c3
Revises: 214a4aa2033d
Create Date: 2024-09-12 11:34:09.499158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2148d33427c3'
down_revision = '214a4aa2033d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('judge', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['judge'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('judge')

    # ### end Alembic commands ###
