"""empty message

Revision ID: 567ef4cd14f0
Revises: c097a7aa656b
Create Date: 2024-09-12 12:17:14.919033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567ef4cd14f0'
down_revision = 'c097a7aa656b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('vehicles_class', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('autonomy', sa.String(length=120), nullable=True),
    sa.Column('weapons', sa.String(length=120), nullable=True),
    sa.Column('passengers', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('autonomy'),
    sa.UniqueConstraint('manufacturer'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('passengers'),
    sa.UniqueConstraint('vehicles_class'),
    sa.UniqueConstraint('weapons')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
