"""empty message

Revision ID: 96cb203b6f2f
Revises: bc1551edb262
Create Date: 2024-09-13 23:03:54.369791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96cb203b6f2f'
down_revision = 'bc1551edb262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_climate_key', type_='unique')
        batch_op.drop_constraint('planets_galactic_location_key', type_='unique')
        batch_op.drop_constraint('planets_government_key', type_='unique')
        batch_op.drop_constraint('planets_native_species_key', type_='unique')
        batch_op.drop_constraint('planets_population_key', type_='unique')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('vehicles_autonomy_key', type_='unique')
        batch_op.drop_constraint('vehicles_manufacturer_key', type_='unique')
        batch_op.drop_constraint('vehicles_passengers_key', type_='unique')
        batch_op.drop_constraint('vehicles_vehicles_class_key', type_='unique')
        batch_op.drop_constraint('vehicles_weapons_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_unique_constraint('vehicles_weapons_key', ['weapons'])
        batch_op.create_unique_constraint('vehicles_vehicles_class_key', ['vehicles_class'])
        batch_op.create_unique_constraint('vehicles_passengers_key', ['passengers'])
        batch_op.create_unique_constraint('vehicles_manufacturer_key', ['manufacturer'])
        batch_op.create_unique_constraint('vehicles_autonomy_key', ['autonomy'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_population_key', ['population'])
        batch_op.create_unique_constraint('planets_native_species_key', ['native_species'])
        batch_op.create_unique_constraint('planets_government_key', ['government'])
        batch_op.create_unique_constraint('planets_galactic_location_key', ['galactic_location'])
        batch_op.create_unique_constraint('planets_climate_key', ['climate'])

    # ### end Alembic commands ###
