"""empty message

Revision ID: bc1551edb262
Revises: e2869b508d14
Create Date: 2024-09-13 23:00:15.135530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1551edb262'
down_revision = 'e2869b508d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_gender_key', type_='unique')
        batch_op.drop_constraint('characters_life_status_key', type_='unique')
        batch_op.drop_constraint('characters_role_key', type_='unique')
        batch_op.drop_constraint('characters_specie_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('characters_specie_key', ['specie'])
        batch_op.create_unique_constraint('characters_role_key', ['role'])
        batch_op.create_unique_constraint('characters_life_status_key', ['life_status'])
        batch_op.create_unique_constraint('characters_gender_key', ['gender'])

    # ### end Alembic commands ###
