"""empty message

Revision ID: c097a7aa656b
Revises: 8190c08ac531
Create Date: 2024-09-12 12:01:10.582244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c097a7aa656b'
down_revision = '8190c08ac531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('galactic_location', sa.String(length=120), nullable=True),
    sa.Column('climate', sa.String(length=120), nullable=True),
    sa.Column('population', sa.String(length=120), nullable=True),
    sa.Column('native_species', sa.String(length=120), nullable=True),
    sa.Column('government', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('climate'),
    sa.UniqueConstraint('galactic_location'),
    sa.UniqueConstraint('government'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('native_species'),
    sa.UniqueConstraint('population')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('specie', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('life_status', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('homeworld_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('life_status'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('role'),
    sa.UniqueConstraint('specie')
    )
    op.drop_table('user')
    op.drop_table('character')
    op.drop_table('planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('planet_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('galactic_location', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('climate', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('population', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('native_species', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('government', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planet_pkey'),
    sa.UniqueConstraint('climate', name='planet_climate_key'),
    sa.UniqueConstraint('galactic_location', name='planet_galactic_location_key'),
    sa.UniqueConstraint('government', name='planet_government_key'),
    sa.UniqueConstraint('name', name='planet_name_key'),
    sa.UniqueConstraint('native_species', name='planet_native_species_key'),
    sa.UniqueConstraint('population', name='planet_population_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('specie', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('life_status', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planet.id'], name='character_homeworld_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='character_pkey'),
    sa.UniqueConstraint('gender', name='character_gender_key'),
    sa.UniqueConstraint('life_status', name='character_life_status_key'),
    sa.UniqueConstraint('name', name='character_name_key'),
    sa.UniqueConstraint('role', name='character_role_key'),
    sa.UniqueConstraint('specie', name='character_specie_key')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('planets')
    # ### end Alembic commands ###
