"""empty message

Revision ID: e2869b508d14
Revises: d39eb126c69c
Create Date: 2024-09-13 22:39:41.594976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2869b508d14'
down_revision = 'd39eb126c69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite__character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    with op.batch_alter_table('favorite__vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite__vehicle', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('favorite__character', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
